### PR TITLE
Vithu Clean Architecture Implementation for SessionUseCase and MessageUseCase

### PR DESCRIPTION
**Pull request by vithushon**
# Description

Implemented Clean Architecture for the SessionUseCase(s) and MessageUseCase(s) as part of secondment to Callhub Connect. Removal of certain files such as MessageWebSocketAccess was a consequence of restructuring the MessageUseCase. Will need reviewers to check if it meets requirements.

Fixes # N/A

## Type of change

- [x] Implementing Clean Architecture (non-breaking change)

# How Has This Been Tested?

Did not run any tests on this code. I did run the frontend application and ensured that functionality remained the same after implementation. The code should function exactly the same way it did prior to CA implementation.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by sarinali — APPROVED** [review]
Great work!! I don't know how I would have done this LOL

Comments: 
- Just some code styling, maybe make the new line close squiggly bracket consistent among all files and new lines ,
otherwise looks good to me!

**Review by sarinali — COMMENTED** [review]
Can you resolve merge conflict so the checks can run?

**Comment by vithushon** [comment]
Yup, will take a look at it tonight and review the code styling + try to resolve the conflict. Will keep you posted!

**Review by zjayee — APPROVED** [review]
Everything works for me locally! Thank you so much for doing this for us!

**Comment by vithushon** [comment]
Great! I think I resolved the merge conflicts. Though, you may need to remove the class ManageWebSocketAccess at a later point as it's just empty and I put it in the driver folder to help resolve the conflict. Should be fine to remove it and keep functionality as required.

**Comment by vithushon** [comment]
Just saw the failed check - It might have to do with the subdirectories in the data_access folder. Not sure how to change the location in which the check looks for the appropriate files.

**Pull request merged**
